spring:
  profiles:
    active: k8s
---
spring:
  profiles: local
  application:
    name: bmw-progress
server:
  port: 20001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    securePortEnabled: true
#    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: k8s
  application:
    name: bmw-progress
server:
  port: 20001
  
    
eureka:
  client:
    service-url:
      defaultZone: http://bmw-register:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

        